import { forwardRef } from "react"

interface Column {
  key: string
  displayName: string
}

interface PrintableTableProps {
  data: Array<{ [key: string]: any }>
  columns: Column[]
}

const PrintableTable = forwardRef<HTMLDivElement, PrintableTableProps>(
  ({ data, columns }, ref) => {
    const currentDateTime = new Date().toLocaleString()

    const getNestedValue = (obj: any, path: string) => {
      return path.split(".").reduce((acc, part) => acc && acc[part], obj)
    }

    return (
      <div ref={ref} className="p-4">
        <div className="w-full p-3">
          <h1 className="text-xl font-semibold">
            {import.meta.env.VITE_APPNAME || ""}
          </h1>
          <p className="text-gray-400 text-sm">
            Generated on: {currentDateTime}
          </p>
        </div>
        <table className="min-w-full bg-white border border-gray-300">
          <thead>
            <tr>
              {columns.map((column, index) => (
                <th
                  key={index}
                  className="px-4 py-2 border-b text-left font-bold"
                >
                  {column.displayName}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {data.map((item, rowIndex) => (
              <tr key={rowIndex} className="hover:bg-gray-100">
                {columns.map((column, colIndex) => (
                  <td key={colIndex} className="px-4 py-2 border-b">
                    {typeof getNestedValue(item, column.key) === "boolean"
                      ? getNestedValue(item, column.key).toString()
                      : getNestedValue(item, column.key)}
                  </td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>
        <div className="print-footer">
          <p>Generated by: {import.meta.env.VITE_APPNAME || ""}</p>
          <p>Generated on: {currentDateTime}</p>
        </div>
      </div>
    )
  }
)

export default PrintableTable
